plugins {
    id 'java'
    id 'net.neoforged.moddev' version '1.0.11'
}

group = 'com.aruru.mldata'
version = '1.0-SNAPSHOT'

neoForge {
    version = "21.1.75"
    parchment {
        minecraftVersion = "1.21.1"
        mappingsVersion = "2024.07.28"
    }
    runs {
        client { client() }
        server { server() }
    }
    mods {
        mldatacollector {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // MySQL Connector & HikariCP Connection Pool
    implementation 'com.mysql:mysql-connector-j:8.4.0'
    implementation 'com.zaxxer:HikariCP:5.1.0'

    // JSON parsing
    implementation 'com.google.code.gson:gson:2.11.0'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
