modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "mldatacollector"
version = "1.0-SNAPSHOT"
displayName = "MLData Collector"
authors = "Aruru"
description = '''
Optimized Minecraft server data collector with MySQL and embedded web server on port 8974.
'''
